alias ls='ls --color=auto'
alias info='info --vi-keys'
alias ssh='TERM=xterm ssh'
alias rdesktop='rdesktop -g 80%'
alias mv='mv -i'
alias screen='screen -U'
alias speed_test='wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip'
alias netsecvnc='vncviewer -autopass seclab15.cs.pdx.edu:04 <<< "unsecnetseccesnu"'
alias surf="surf -bsu 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)'"
alias rdesktop-ts="rdesktop -u hamlinb -d cecs -p - -K -x m -g 100% localhost"
alias vimake="vim -c make -c 'botright cwindow'"
