#
# ~/.bash_profile
#

[[ -e ~/.bashrc ]] && . ~/.bashrc

export VISUAL=vim
export CLICOLOR=1

#Make xinit automatic at login.
#[[ -n /tmp/.X0-lock ]] && xinit
if [ -e /home/hamlinb/.nix-profile/etc/profile.d/nix.sh ]; then . /home/hamlinb/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
