alias ls='ls --color=auto'
alias info='info --vi-keys'
alias ssh='TERM=xterm ssh'
alias rdesktop='rdesktop -g 80%'
alias mv='mv -i'
alias screen='screen -U'
alias speed_test='wget --report-speed=bits -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip'
alias netsecvnc='vncviewer -autopass seclab15.cs.pdx.edu:04 <<< "unsecnetseccesnu"'
alias surf="surf -bsu 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)'"
alias rdesktop-ts="rdesktop -u hamlinb -d cecs -p - -K -x m -g 100% localhost"
alias vimake="vim -c make -c 'botright cwindow'"
alias play="mplayer -vo null"
alias w3mgodoc='w3m -T text/html <<< godoc -html'
alias cryptol2='~/src/cryptol/dist/build/cryptol/cryptol'
alias primary2clipboard='xclip -o -selection p | xclip -i -selection c'
#alias ghci="ghci 2>&1 | HsColour"
