so ~/.vim/plugins.vimrc
colo candy

syn on
set nocompatible
set number
set laststatus=2

set wildmode=longest,full
set wildmenu

filetype plugin indent on

let mapleader='\<Space>'

so ~/.vim/colors.vimrc
so ~/.vim/airline.vimrc
so ~/.vim/signify.vimrc
so ~/.vim/w3m.vimrc
so ~/.vim/haskellmode.vimrc
